apiVersion: v1
kind: Service # kind of K8S Object
metadata:
  name: petclinic-service
spec:
  selector:
    app: petclinic # the same label we used for the petclinic deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080